apiVersion: v1
kind: Pod
metadata:
  name: ansible-master
  labels:
    role: master
spec:
  containers:
    - name: master
      image: ubuntu:20.04
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 3600; done"]
      tty: true
