apiVersion: v1
kind: Pod
metadata:
  name: ansible-node1
  labels:
    role: node
spec:
  containers:
    - name: node1
      image: ubuntu:20.04
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 3600; done"]
      tty: true
